name: Build & run maman11/task1 with Makefile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # manual trigger

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install -y build-essential  # includes gcc & make

      # Compile *and* execute using the Makefile
      - name: Build and run via Makefile
        working-directory: maman11/task1
        run: |
          set -x
          make run   # compiles (if needed) then runs, writes output.txt

      # Upload only the program’s output
      - name: Upload output.txt
        uses: actions/upload-artifact@v4
        with:
          name: palindrome-output
          path: maman11/task1/output.txt
          retention-days: 90   # adjust as you like
