name: Build & run maman11/task1 with Makefile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install -y build-essential   # gcc + make

      - name: Clean, build and run via Makefile
        working-directory: maman11/task1
        run: |
          set -x
          make clean            # toss any pre‑built binary
          make run              # rebuild on Linux and execute

      - name: Upload output.txt
        uses: actions/upload-artifact@v4
        with:
          name: palindrome-output
          path: maman11/task1/output.txt
          retention-days: 90